stages:
  - install-dependencies
  - build
  - deploy

dependencies:
  stage: install-dependencies
  image: node:12
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
  script: 
    - yarn
  rules:
    - changes: 
      - yarn.lock
      when: always

build:
  stage: build
  image: node:12
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
  script:
    - yarn lint
    - yarn build
  artifacts:
    paths:
      - build
    expire_in: 1 day

deploy:
  stage: deploy
  image: alpine
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -e 'ssh -p 622' -ravO --delete build/ $SSH_USER@01.sv64.xyz:/var/www/nth/test
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      when: on_success
 
