stages:
  - build-app

build app:
  stage: build-app
  image: node:12
  script:
    - yarn
    - yarn lint
    - yarn build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - build
    expire_in: 1 day
